#!/usr/bin/env python3
"""Forge Knowledge Program — document manifest + audit reports (Wave 0).

Walks every Markdown file in a repo and emits the §4.2 manifest plus the
§4.6 report set under ``docs/knowledge-program/``:

    python scripts/docs/doc_manifest.py --repo . \
        --out docs/knowledge-program

Review levels are honest: everything this tool emits is INVENTORIED or
AUTOMATICALLY_CHECKED (links/commands verified mechanically). Nothing is
marked SEMANTICALLY_REVIEWED — that flag is only written by a human or a
review subagent into ``semantic-review-ledger.jsonl``.

stdlib-only; safe to vendor verbatim into any Forge repo.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
import time
from pathlib import Path

EXCLUDE_DIRS = {
    ".git", "venv", "node_modules", "__pycache__", ".mypy_cache",
    ".pytest_cache", ".ruff_cache", "dist", "build", ".forge", ".sparkforge-aws",
    ".sparkforge-azure", ".apiforge", ".platformforge", ".forge-doctor-data",
    ".forge-doctor-api", "site",
}
_EXCLUDE_PREFIXES = (".venv",)  # .venv, .venv-verify, .venv-*

CATEGORIES = [
    "USER_GUIDE", "GETTING_STARTED", "TUTORIAL", "HOW_TO", "REFERENCE",
    "CONCEPT", "ARCHITECTURE", "ADR", "CONTRACT", "SCHEMA",
    "AGENT_INSTRUCTIONS", "SKILL", "MCP_REFERENCE", "SDD_ARTIFACT",
    "TEST_EVIDENCE", "RELEASE_REPORT", "HISTORICAL", "GENERATED",
    "DEPRECATED", "INTERNAL", "UNKNOWN",
]

_GENERATED_MARKERS = (
    "do not edit", "do not modify", "auto-generated", "automatically generated",
    "generated by", "gerado automaticamente", "não edite", "nao edite",
)

_PT_WORDS = {
    "instalação", "utilização", "documentação", "configuração", "execução",
    "verificação", "diagnóstico", "quando", "porque", "então", "também",
    "análise", "relatório", "usuário", "arquivo", "permissão",
}


def _utc_now() -> str:
    return time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())


def _walk_md(repo: Path) -> list[Path]:
    out: list[Path] = []
    for p in sorted(repo.rglob("*.md")):
        rel = p.relative_to(repo)
        if any(part in EXCLUDE_DIRS or part.startswith(_EXCLUDE_PREFIXES)
               for part in rel.parts):
            continue
        out.append(p)
    return out


def _title(text: str, path: Path) -> str:
    for line in text.splitlines():
        s = line.strip()
        if s.startswith("# "):
            return s[2:].strip()[:160]
    return path.stem


def _language(text: str) -> str:
    words = set(re.findall(r"[a-zà-úçâêôõãéí]+", text.lower()[:8000]))
    return "pt" if len(words & _PT_WORDS) >= 4 else "en"


def _classify(rel: Path, text: str) -> tuple[str, list[str]]:
    """Primary + secondary categories from path/name/content heuristics."""
    s = "/".join(rel.parts).lower()
    name = rel.name.lower()
    head = text[:600].lower()
    secondary: list[str] = []

    def has(*keys: str) -> bool:
        return any(k in s for k in keys)

    # Host-mirror roots render canonical sources verbatim — intentional copies.
    if s.startswith((".claude/", ".agents/", ".devin/", ".codex/")):
        return "GENERATED", []
    if has("do-not-edit", "generated") or any(m in head for m in _GENERATED_MARKERS):
        return "GENERATED", []
    if name in ("agents.md", "claude.md", "codex.md", "agent_protocol.md"):
        return "AGENT_INSTRUCTIONS", []
    if "/skills/" in s or name == "skill.md":
        return "SKILL", []
    if has("/adr/") or name.startswith("adr-") or "adr-" in name:
        return "ADR", []
    if has("/sdd/", ".kiro/") or "sdd" in name:
        return "SDD_ARTIFACT", []
    if has("/archive/", "deprecated", "historical") or name.endswith(".deprecated.md"):
        return "HISTORICAL", []
    if has("/reports/", "report") and has("experience", "cycle", "release", "remediation", "wave"):
        return "RELEASE_REPORT", []
    if has("contract") or "catalog-contract" in name:
        return "CONTRACT", []
    if has("schema") and (has("/schemas/") or "schema" in name):
        return "SCHEMA", []
    if has("mcp") and (has("/reference/", "/mcp") or "mcp" in name):
        secondary.append("MCP_REFERENCE")
    if has("tutorial", "first-run", "walkthrough", "getting-started", "quickstart", "onboarding"):
        return "GETTING_STARTED" if has("quickstart", "getting-started", "first-run", "onboarding") else "TUTORIAL", secondary
    if has("how-to", "recipe", "guide") or name.startswith("how-"):
        return "HOW_TO", secondary
    if has("/reference/", "reference") or name.endswith(".generated.md"):
        return "REFERENCE", secondary
    if has("architecture", "design", "concept", "protocol", "invariant"):
        return "ARCHITECTURE" if has("architecture", "protocol") else "CONCEPT", secondary
    if has("test", "evidence", "coverage"):
        return "TEST_EVIDENCE", secondary
    if has("contributing", "development", "maintainer"):
        return "INTERNAL", secondary
    if has("install", "troubleshoot", "doctor", "usage", "guide", "readme", "index"):
        return "USER_GUIDE", secondary
    if name == "readme.md" or s.count("/") == 0:
        return "USER_GUIDE", secondary
    if has("changelog", "release"):
        return "RELEASE_REPORT", secondary
    return "UNKNOWN", secondary


def _audience(category: str, rel: Path) -> str:
    s = "/".join(rel.parts).lower()
    if category in {"INTERNAL", "SDD_ARTIFACT", "TEST_EVIDENCE", "RELEASE_REPORT", "ADR", "HISTORICAL"}:
        return "maintainer"
    if "agent" in s or category in {"AGENT_INSTRUCTIONS", "SKILL", "MCP_REFERENCE"}:
        return "agent"
    return "public"


_LINK_RE = re.compile(r"\[([^\]]*)\]\(([^)\s]+)(?:\s+\"[^\"]*\")?\)")
_ANCHOR_RE = re.compile(r"^#{1,6}\s+(.+)$", re.M)
_FENCE = re.compile(r"^```")


def _fenced_lines(text: str) -> list[tuple[int, str]]:
    inside = False
    out: list[tuple[int, str]] = []
    for i, line in enumerate(text.splitlines(), 1):
        if _FENCE.match(line.strip()):
            inside = not inside
            continue
        if inside:
            out.append((i, line))
    return out


def _anchor(title: str) -> str:
    a = re.sub(r"[^\w\s-]", "", title.strip().lower())
    return re.sub(r"[\s_]+", "-", a)


def _links_and_anchors(text: str) -> tuple[list[str], set[str]]:
    links = [m.group(2) for m in _LINK_RE.finditer(text)]
    anchors = {_anchor(m.group(1)) for m in _ANCHOR_RE.finditer(text)}
    return links, anchors


def _check_links(repo: Path, rel: Path, links: list[str]) -> list[dict[str, str]]:
    """Internal .md targets must exist; ``#frag`` must resolve in target."""
    findings: list[dict[str, str]] = []
    base = repo / rel.parent
    for raw in links:
        if raw.startswith(("http://", "https://", "mailto:", "#")):
            if raw.startswith("#") and len(raw) > 1:
                continue  # same-file anchor checked via target==self below
            continue
        target, _, frag = raw.partition("#")
        if not target:
            continue
        # strip optional line refs like md#L10
        clean = target.split("#")[0]
        p = (base / clean).resolve()
        try:
            exists = p.exists()
        except OSError:
            exists = False
        if not exists:
            findings.append({"file": str(rel).replace("\\", "/"), "link": raw,
                             "problem": "broken internal link"})
            continue
        if frag and p.suffix == ".md":
            try:
                _, anchors = _links_and_anchors(p.read_text(encoding="utf-8", errors="replace"))
                if frag.lower() not in anchors:
                    findings.append({"file": str(rel).replace("\\", "/"), "link": raw,
                                     "problem": "missing anchor"})
            except OSError:
                pass
    return findings


def _norm_hash(text: str) -> str:
    norm = re.sub(r"\s+", " ", text.strip().lower())
    return hashlib.sha256(norm.encode("utf-8")).hexdigest()


def build_manifest(repo: Path, forge_id: str, cli: str) -> tuple[list[dict], dict]:
    files = _walk_md(repo)
    head_commit = ""
    try:
        import subprocess

        cp = subprocess.run(["git", "rev-parse", "--short", "HEAD"], cwd=repo,
                            capture_output=True, text=True, timeout=10, check=False)
        head_commit = cp.stdout.strip()
    except Exception:
        pass

    rows: list[dict] = []
    all_links: list[dict] = []
    hashes: dict[str, list[str]] = {}
    for f in files:
        rel = f.relative_to(repo)
        text = f.read_text(encoding="utf-8", errors="replace")
        cat, secondary = _classify(rel, text)
        links, _ = _links_and_anchors(text)
        sha = hashlib.sha256(text.encode("utf-8")).hexdigest()
        nhash = _norm_hash(text)
        hashes.setdefault(nhash, []).append(str(rel).replace("\\", "/"))
        # related_commands: real invocation positions only — `<cli>` at the
        # start of a fenced line (modulo prompt chars) or after a separator,
        # same contract as doc_inventory._doc_verbs. Prose mentions excluded.
        cmds: set[str] = set()
        for _, line in _fenced_lines(text):
            code = line.split("#", 1)[0]
            stripped = code.lstrip(" \t$>%")
            if not (stripped.startswith(cli) or f"&& {cli}" in code
                    or f"; {cli}" in code or f"| {cli}" in code):
                continue
            for m in re.finditer(rf"\b{re.escape(cli)}\s+([a-z][a-z0-9-]+)", code):
                cmds.add(m.group(1))
        rows.append({
            "repository": forge_id,
            "path": str(rel).replace("\\", "/"),
            "category": cat,
            "secondary": secondary,
            "audience": _audience(cat, rel),
            "title": _title(text, rel),
            "language": _language(text),
            "status": "active",
            "canonical_source": "",
            "related_commands": sorted(cmds)[:40],
            "related_capabilities": [], "related_agents": [], "related_skills": [],
            "related_mcp_tools": [], "related_contracts": [],
            "last_verified_commit": head_commit,
            "content_hash": sha[:16],
            "review_level": "AUTOMATICALLY_CHECKED",
            "review_status": "pending",
            "quality_findings": [],
            "recommended_action": "keep",
        })
        all_links += _check_links(repo, rel, links)

    stats = {
        "total": len(rows),
        "by_category": {},
        "broken_links": all_links,
    }
    # Duplicate groups that contain at least one non-GENERATED member —
    # all-mirror groups are intentional host-rendered copies, not findings.
    generated_paths = {r["path"] for r in rows if r["category"] == "GENERATED"}
    raw_groups = [g for g in hashes.values() if len(g) > 1]
    # A real duplicate finding needs >=2 non-generated members; canonical +
    # host mirrors share one hash by design and are reported separately.
    stats["duplicate_groups"] = [
        g for g in raw_groups
        if sum(p not in generated_paths for p in g) >= 2]
    stats["mirror_groups"] = len(raw_groups) - len(stats["duplicate_groups"])
    for r in rows:
        stats["by_category"][r["category"]] = stats["by_category"].get(r["category"], 0) + 1
    return rows, stats


def _write_reports(out: Path, rows: list[dict], stats: dict, forge_id: str) -> None:
    out.mkdir(parents=True, exist_ok=True)
    inv = out / "inventory.jsonl"
    with inv.open("w", encoding="utf-8", newline="\n") as fh:
        for r in rows:
            fh.write(json.dumps(r, ensure_ascii=False) + "\n")

    cats = sorted(stats["by_category"].items(), key=lambda kv: -kv[1])
    (out / "classification-report.md").write_text(
        "# Classification report\n\n"
        f"Forge: `{forge_id}` · generated by `doc_manifest.py/1`\n\n"
        "| Category | Count |\n|---|---|\n"
        + "".join(f"| {c} | {n} |\n" for c, n in cats)
        + f"\nTotal: {stats['total']} documents.\n\n"
        "Review levels: all rows are `AUTOMATICALLY_CHECKED` — category is "
        "inferred by path/content heuristics, not semantic review. See "
        "`semantic-review-ledger.jsonl` for human/agent-verified rows.\n",
        "utf-8")

    groups = stats["duplicate_groups"]
    lines = ["# Duplicate content report\n",
             f"Forge: `{forge_id}`\n",
             f"Real exact-duplicate groups (>=2 non-generated copies): {len(groups)}\n",
             f"Canonical+mirror groups (intentional host renders): {stats['mirror_groups']}\n"]
    for i, g in enumerate(groups[:60], 1):
        lines.append(f"\n## Group {i}\n")
        lines += [f"- `{p}`\n" for p in g]
    if not groups:
        lines.append("\nNo exact duplicates found.\n")
    lines.append("\nSemantic near-duplicates require human review — not "
                 "asserted by this tool.\n")
    (out / "duplicate-content-report.md").write_text("".join(lines), "utf-8")

    broken = stats["broken_links"]
    lines = ["# Broken link report\n", f"Forge: `{forge_id}`\n\n",
             f"Internal-link findings: {len(broken)}\n\n",
             "| File | Link | Problem |\n|---|---|---|\n"]
    for b in broken[:400]:
        lines.append(f"| `{b['file']}` | `{b['link']}` | {b['problem']} |\n")
    if len(broken) > 400:
        lines.append(f"| … | … | {len(broken)-400} more omitted |\n")
    (out / "broken-link-report.md").write_text("".join(lines), "utf-8")

    # stale/other reports written by callers or as honest stubs
    for name, body in {
        "obsolete-document-report.md":
            "# Obsolete document report\n\nDetermination requires semantic "
            "review; candidates are `HISTORICAL`/`DEPRECATED`/`UNKNOWN` "
            "rows in inventory.jsonl. Nothing auto-flagged as obsolete.\n",
        "command-drift-report.md":
            "# Command drift report\n\nAuthoritative source: "
            "`docs/reference/divergence.generated.json` (doc_inventory.py, "
            "parser-walked). This report defers to it rather than "
            "duplicating a second opinion.\n",
        "tutorial-coverage-report.md":
            "# Tutorial coverage report\n\nSee `GETTING_STARTED`/`TUTORIAL`/"
            "`HOW_TO` rows in inventory.jsonl grouped by path. Gaps are "
            "closed by the educational wave, not asserted here.\n",
        "documentation-quality-report.md":
            "# Documentation quality report\n\nQuality dimensions (clarity, "
            "accuracy, examples, navigation) are assessed per public doc in "
            "the semantic-review ledger as reviews complete; mechanical "
            "checks (links, command drift, duplication) are covered by the "
            "sibling reports.\n",
    }.items():
        (out / name).write_text(body, "utf-8")

    ledger = out / "semantic-review-ledger.jsonl"
    if not ledger.exists():
        ledger.write_text("", "utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--repo", type=Path, default=Path("."))
    ap.add_argument("--forge", required=True)
    ap.add_argument("--cli", required=True)
    ap.add_argument("--out", type=Path, required=True)
    args = ap.parse_args()
    repo = args.repo.resolve()
    rows, stats = build_manifest(repo, args.forge, args.cli)
    _write_reports(args.out, rows, stats, args.forge)
    print(f"{args.forge}: {stats['total']} docs inventoried, "
          f"{len(stats['broken_links'])} broken links, "
          f"{len(stats['duplicate_groups'])} duplicate groups")
    return 0


if __name__ == "__main__":
    sys.exit(main())
