#!/usr/bin/env python3
"""Forge Knowledge Program — canonical documentation index (Wave 2).

Generates ``docs/INDEX.md`` from ``docs/knowledge-program/inventory.jsonl``
(produced by ``doc_manifest.py``). The information architecture is fixed:

    Learn / Use / Reference / Understand / Operate / Contribute / Archive

Rules:
- generated, never hand-edited (regenerate after doc changes);
- beginners see Learn first — the full corpus stays under Archive,
  categorized but discoverable;
- GENERATED host mirrors and VENDORED_UPSTREAM trees are not listed
  (their canonical sources are);
- each entry links the doc and carries its category tag.

stdlib-only; safe to vendor verbatim into any Forge repo.
"""
from __future__ import annotations

import argparse
import json
from collections import defaultdict
from pathlib import Path

SCHEMA = "forge/DocIndex/v1"

SECTION_ORDER = [
    "Learn", "Use", "Reference", "Understand", "Operate", "Contribute",
    "Archive",
]

CATEGORY_TO_SECTION = {
    "GETTING_STARTED": "Learn",
    "TUTORIAL": "Learn",
    "CONCEPT": "Understand",
    "ARCHITECTURE": "Understand",
    "ADR": "Understand",
    "HOW_TO": "Use",
    "USER_GUIDE": "Use",
    "REFERENCE": "Reference",
    "CONTRACT": "Reference",
    "SCHEMA": "Reference",
    "MCP_REFERENCE": "Reference",
    "AGENT_INSTRUCTIONS": "Contribute",
    "SKILL": "Contribute",
    "INTERNAL": "Contribute",
    "OPERATE": "Operate",
    "RUNBOOK": "Operate",
    "HISTORICAL": "Archive",
    "DEPRECATED": "Archive",
    "SDD_ARTIFACT": "Archive",
    "TEST_EVIDENCE": "Archive",
    "RELEASE_REPORT": "Archive",
    "GENERATED": "Archive",
    "UNKNOWN": "Archive",
}

# Path fragments that mark operational docs even when heuristics file them
# under another category.
_OPERATE_HINTS = (
    "troubleshoot", "runbook", "operat", "incident", "doctor",
    "repair", "uninstall", "monitor", "observab",
)


def _section_for(row: dict) -> str:
    path = row["path"].lower()
    if row["category"] not in ("HISTORICAL", "DEPRECATED", "SDD_ARTIFACT",
                              "TEST_EVIDENCE", "RELEASE_REPORT", "GENERATED"):
        if any(h in path for h in _OPERATE_HINTS):
            return "Operate"
    return CATEGORY_TO_SECTION.get(row["category"], "Archive")


def build_index(rows: list[dict], forge: str) -> str:
    sections: dict[str, list[dict]] = defaultdict(list)
    for r in rows:
        if r["category"] == "GENERATED" or "VENDORED_UPSTREAM" in r["secondary"]:
            continue
        sections[_section_for(r)].append(r)

    out = [
        f"# {forge} — Documentation Index",
        "",
        "<!-- generated by scripts/docs/doc_index.py from",
        "docs/knowledge-program/inventory.jsonl — do not hand-edit -->",
        "",
        "Canonical entry points only; host mirrors (`.claude/`, `.agents/`,",
        "`.devin/`, `.codex/`) and vendored trees render these same sources.",
        "",
    ]
    blurbs = {
        "Learn": "Start here — installation, first run, tutorials.",
        "Use": "Task-oriented guides and workflows.",
        "Reference": "Command, contract, schema and tool references.",
        "Understand": "Concepts, architecture and design decisions.",
        "Operate": "Troubleshooting, doctor/repair, observability.",
        "Contribute": "Agent instructions, skills and internal process.",
        "Archive": "Historical, deprecated, generated and evidence docs "
        "(preserved, not entry points).",
    }
    for sec in SECTION_ORDER:
        items = sorted(sections.get(sec, []), key=lambda r: r["path"])
        out.append(f"## {sec}")
        out.append("")
        out.append(f"_{blurbs[sec]}_")
        out.append("")
        if not items:
            out.append("_none yet_")
            out.append("")
            continue
        # group by top-level docs folder to keep long sections scannable
        groups: dict[str, list[dict]] = defaultdict(list)
        for r in items:
            parts = r["path"].split("/")
            grp = parts[1] if parts[0] == "docs" and len(parts) > 2 else \
                (parts[0] if len(parts) > 1 else ".")
            groups[grp].append(r)
        for grp in sorted(groups):
            if len(groups) > 1:
                out.append(f"### {grp}/")
                out.append("")
            for r in sorted(groups[grp], key=lambda r: r["path"]):
                title = r["title"] or Path(r["path"]).stem
                tag = f" `{r['category']}`" if sec == "Archive" else ""
                # INDEX.md lives in docs/: strip the prefix, else go up.
                href = (r["path"][5:] if r["path"].startswith("docs/")
                        else "../" + r["path"])
                out.append(f"- [{title}]({href}){tag}")
            out.append("")
    return "\n".join(out).rstrip() + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo", type=Path, default=Path("."))
    ap.add_argument("--forge", required=True)
    ap.add_argument("--inventory", type=Path,
                    default=Path("docs/knowledge-program/inventory.jsonl"))
    ap.add_argument("--out", type=Path, default=Path("docs/INDEX.md"))
    args = ap.parse_args()

    inv = args.repo / args.inventory
    rows = [json.loads(l) for l in
            inv.read_text("utf-8").splitlines() if l.strip()]
    md = build_index(rows, args.forge)
    out = args.repo / args.out
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(md, encoding="utf-8", newline="\n")
    print(f"wrote {out} ({len(rows)} inventoried, "
          f"{md.count('- [')} entries)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
