#!/usr/bin/env python3
"""Generate the deterministic "Which Forge Should I Use?" hub page.

Source of truth: ``forge-knowledge/*.json`` (ForgeKnowledge/v1) — real
``appropriate_for``/``inappropriate_for``/``intents``/``examples`` contracts.
Regenerate after changing a knowledge package; never hand-edit the output.

stdlib-only.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
KNOWLEDGE = ROOT / "forge-knowledge"
OUT = ROOT / "docs" / "hub" / "which-forge.md"


def main() -> int:
    packs = sorted(
        (json.loads(p.read_text("utf-8")) for p in KNOWLEDGE.glob("*.json")),
        key=lambda d: d["id"],
    )
    out = [
        "# Which Forge Should I Use?",
        "",
        "<!-- generated by scripts/docs/gen_hub.py from forge-knowledge/*.json",
        "— deterministic, no LLM; do not hand-edit -->",
        "",
        "Decisão por contrato declarado (`appropriate_for`/`inappropriate_for`",
        "de cada ForgeKnowledge/v1). Em dúvida: `theforge knowledge list` e",
        "`theforge capabilities discover --capability <id>`.",
        "",
        "## Decisão rápida",
        "",
        "| Se o seu problema é… | Use | Não use para… |",
        "|---|---|---|",
    ]
    for d in packs:
        app = "; ".join(d.get("appropriate_for") or ["—"])
        inapp = "; ".join(d.get("inappropriate_for") or ["—"])
        # keep cells one-line
        app = " ".join(app.split())[:220]
        inapp = " ".join(inapp.split())[:160]
        out.append(f"| {app} | **{d['id']}** | {inapp} |")
    out += [
        "",
        "## Por forja",
        "",
    ]
    for d in packs:
        out.append(f"### {d['name']} (`{d['id']}`)")
        out.append("")
        out.append(d.get("summary", "").strip())
        out.append("")
        if d.get("intents"):
            out.append("**Intents declarados:** " +
                       ", ".join(f"`{i}`" for i in d["intents"]))
            out.append("")
        if d.get("composes_with"):
            out.append("**Compõe com:** " +
                       ", ".join(f"`{c}`" for c in d["composes_with"]))
            out.append("")
        if d.get("limitations_note"):
            out.append(f"**Limite honesto:** {d['limitations_note']}")
            out.append("")
        if d.get("examples"):
            ex = d["examples"][0]
            cmd = ex.get("command") if isinstance(ex, dict) else str(ex)
            out.append(f"```bash\n{cmd}\n```")
            out.append("")
        out.append(f"- pacote: `{d.get('package')}` · binário: "
                   f"`{d.get('binary')}` · python `{d.get('python')}`")
        out.append("")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(out).rstrip() + "\n", encoding="utf-8",
                   newline="\n")
    print(f"wrote {OUT} ({len(packs)} forges)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
