"""``theforge provider init`` scaffold (Cycle 3 Wave M1): writes a minimal,
stdlib-only Forge Protocol v1 provider — manifest template, protocol
skeleton, a conformance test driving :func:`theforge.conformance.check_provider`
and a README with the registration snippet. Nothing is installed globally
and nothing outside the target directory is written; registering the
provider is a manual, deliberate step (a TOML entry in a providers.toml).
"""

import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

from theforge.contracts.manifest import CAPABILITY_ID, PROVIDER_ID
from theforge.errors import UsageError

_PROVIDER_PY = '''\
#!/usr/bin/env python3
"""{id} — Forge Protocol v1 provider skeleton (generated by `theforge provider init`).

stdlib only: reads the Request JSON from stdin, answers a Response envelope on
stdout and always exits 0 — a crash reaches the core as a transport error.
Implement the real work in `op_execute`; keep `manifest.json` truthful.
"""
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

MANIFEST = json.loads(
    Path(__file__).with_name("manifest.json").read_text(encoding="utf-8"))
PRODUCER = {{"id": MANIFEST["id"], "version": MANIFEST["version"]}}
CAPABILITIES = {{c["id"]: c for c in MANIFEST["capabilities"]}}


def _utc_now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _respond(request: dict, *, status: str, payload: dict | None = None,
             error: dict | None = None) -> dict:
    response = {{
        "protocol": "forge/v1",
        "kind": "Response",
        "request_id": request.get("request_id", ""),
        "op": request.get("op"),
        "producer": PRODUCER,
        "status": status,
        "payload": payload or {{}},
        "limitations": [],
        "unknowns": [],
    }}
    if error is not None:
        response["error"] = error
    return response


def op_execute(payload: dict) -> dict:
    """Return an ExecutionResult dict for the requested capability/action.

    The context files are relative to `payload["task"]["workspace_root"]`;
    read only the items listed in `payload["context"]["files"]`, never
    outside the workspace root. Write artifacts under the current working
    directory (the run's work dir) and declare each with its sha256.
    """
    capability = payload["capability"]
    # TODO: real work. This skeleton reports an empty, honest result.
    return {{
        "schema": "theforge/ExecutionResult/v1",
        "producer": PRODUCER,
        "created_at": _utc_now(),
        "status": "ok",
        "findings": [],
        "evidence": [],
        "artifacts": [],
        "limitations": [
            f"{{capability}}: skeleton provider — no work performed yet"],
        "unknowns": [],
    }}


def _handle(request: dict) -> dict:
    op = request.get("op")
    payload = request.get("payload") or {{}}
    if op == "describe":
        return _respond(request, status="ok", payload=MANIFEST)
    if op == "health":
        return _respond(request, status="ok",
                        payload={{"status": "ok", "checks": []}})
    if op == "execute":
        capability = payload.get("capability", "")
        declared = CAPABILITIES.get(capability)
        if declared is None:
            return _respond(request, status="refused", error={{
                "code": "{prefix}-UNKNOWN-CAPABILITY",
                "detail": f"unknown capability {{capability!r}}"}})
        action = payload.get("action", "")
        if action not in declared.get("actions", []):
            return _respond(request, status="refused", error={{
                "code": "{prefix}-UNKNOWN-ACTION",
                "detail": f"unknown action {{action!r}} for {{capability}}"}})
        return _respond(request, status="ok", payload=op_execute(payload))
    return _respond(request, status="refused", error={{
        "code": "{prefix}-UNKNOWN-OP",
        "detail": f"unsupported op {{op!r}}"}})


def main() -> int:
    try:
        request = json.loads(sys.stdin.read())
    except json.JSONDecodeError as exc:
        print(json.dumps(_respond({{"request_id": "", "op": None}},
                                  status="error", error={{
                                      "code": "{prefix}-BAD-REQUEST",
                                      "detail": f"stdin is not a JSON request: {{exc}}"}})))
        return 0
    if request.get("kind") != "Request" or request.get("protocol") != "forge/v1":
        print(json.dumps(_respond(request, status="refused", error={{
            "code": "{prefix}-PROTOCOL",
            "detail": f"unsupported protocol {{request.get('protocol')!r}}"}})))
        return 0
    print(json.dumps(_handle(request)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''

_MANIFEST_JSON = '''\
{{
  "schema": "theforge/ForgeManifest/v1",
  "id": "{id}",
  "version": "0.1.0",
  "protocols": ["forge/v1"],
  "ops": ["describe", "health", "execute"],
  "capabilities": [
    {{
      "id": "{capability}",
      "description": "TODO: what this capability does",
      "actions": ["run"],
      "default_action": "run",
      "state": "heuristic",
      "operation_class": "read_only",
      "signals": {{
        "keywords": ["{keyword}"]
      }},
      "context": {{"excerpts": false, "requests": false}},
      "accepts_handoff": false
    }}
  ],
  "execution": {{"local": true, "offline": true, "requires_network": false,
                "deterministic": true}},
  "features": [],
  "context_revalidation": "none",
  "limitations": [
    "skeleton generated by `theforge provider init`: implement execute for real",
    "signals are placeholders: declare keywords/globs that actually discriminate"
  ]
}}
'''

_TEST_CONFORMANCE = '''\
"""Conformance gate for {id}: drives the shipped kit.

Run with the interpreter that has `theforge` installed:

    python -m pytest test_conformance.py
"""

import sys
from pathlib import Path

from theforge.conformance import check_provider

ARGV = [sys.executable, str(Path(__file__).resolve().parent / "provider.py")]


def test_protocol_conformance() -> None:
    report = check_provider(ARGV)
    assert report.ok, [f"{{c.id}}: {{c.detail}}" for c in report.checks
                       if c.status == "fail"]
'''

_README = '''\
# {id}

Provider do Forge Protocol v1 gerado por `theforge provider init`.

## Arquivos
- `manifest.json` — o que o provider declara (`describe` responde com ele). Edite
  id, versão, capabilities e sinais de verdade.
- `provider.py` — esqueleto stdlib do protocolo (stdin JSON → stdout JSON,
  sempre exit 0). Implemente o trabalho real em `op_execute`.
- `test_conformance.py` — gate de conformidade (kit do core).

## Registrar (manual, nada é instalado automaticamente)

Adicione ao `providers.toml` do usuário (`%APPDATA%\\theforge\\providers.toml`
no Windows, `$XDG_CONFIG_HOME/theforge/providers.toml` ou
`~/.config/theforge/providers.toml` no POSIX) ou do projeto
(`.forge/config/providers.toml`, entra como `unverified`):

```toml
[[providers]]
id = "{id}"
argv = ["{python}", "{provider_py}"]
trust = "local"
```

Depois: `theforge registry refresh` e `theforge providers health`.

## Conformidade

```
python -m pytest test_conformance.py
# ou, sem pytest:
theforge provider check -- "{python}" "{provider_py}"
```

Guia completo: `docs/provider-authoring.md` do repositório The Forge.
'''


@dataclass(frozen=True, kw_only=True)
class ScaffoldResult:
    """What ``init_provider`` wrote plus the registration hint to display."""

    directory: Path
    files: list[Path] = field(default_factory=list)
    argv: list[str] = field(default_factory=list)
    provider_id: str = ""
    capability: str = ""


def _default_capability(provider_id: str) -> str:
    """``acme-forge`` → ``acme.describe``; falls back to a UsageError when the
    provider id cannot lend a namespace."""
    namespace = re.sub(r"[^a-z0-9]", "", provider_id.split("-")[0])
    if not namespace or not namespace[0].isalpha():
        raise UsageError(
            f"cannot derive a capability namespace from provider id {provider_id!r}; "
            "pass --capability <namespace.subject>")
    return f"{namespace}.describe"


def _error_prefix(provider_id: str) -> str:
    """Provider-native error prefix: `acme-forge` → `ACME` (core-prefixed
    codes stay the core's family; native codes carry their own)."""
    prefix = re.sub(r"[^A-Z0-9]", "", provider_id.split("-")[0].upper())
    return prefix[:12] or "PROVIDER"


def init_provider(
    directory: Path, provider_id: str, *, capability: str | None = None,
) -> ScaffoldResult:
    """Write the scaffold under ``directory``; refuses to overwrite anything."""
    if not PROVIDER_ID.match(provider_id):
        raise UsageError(
            f"invalid provider id {provider_id!r}: expected {PROVIDER_ID.pattern}")
    capability = capability or _default_capability(provider_id)
    if not CAPABILITY_ID.match(capability):
        raise UsageError(
            f"invalid capability id {capability!r}: expected {CAPABILITY_ID.pattern}")
    directory = directory.resolve()
    if directory.exists() and any(directory.iterdir()):
        raise UsageError(
            f"{directory} is not empty: provider init only writes into an empty "
            "or new directory")
    directory.mkdir(parents=True, exist_ok=True)
    prefix = _error_prefix(provider_id)
    provider_py = directory / "provider.py"
    files = {
        provider_py: _PROVIDER_PY.format(id=provider_id, prefix=prefix),
        directory / "manifest.json": _MANIFEST_JSON.format(
            id=provider_id, capability=capability,
            keyword=capability.split(".")[0]),
        directory / "test_conformance.py": _TEST_CONFORMANCE.format(id=provider_id),
        directory / "README.md": _README.format(
            id=provider_id, python=sys.executable,
            provider_py=provider_py),
    }
    for path, content in files.items():
        path.write_text(content, encoding="utf-8", newline="\n")
    return ScaffoldResult(
        directory=directory, files=list(files),
        argv=[sys.executable, str(provider_py)],
        provider_id=provider_id, capability=capability)
